### ISSUE TITLE
Great Work ! Can you add  SendMessageA 

### ISSUE THREAD

**Issue by auuuux** [waitingsong/node-win32-api#10]
Great Work !
Can you add the following API?
PostMessageA 
SendMessageA 

They are very useful

**Comment by zuozishi** [comment]
+1
And keybd_event.

**Comment by waitingsong** [comment]
pls try user32.SendMessageW() with v3.8.0

commit: a3036d6

**Comment by waitingsong** [comment]
pls try user32.PostMessageW() with `v3.9.0`

commit: 7b02830c
