### ISSUE TITLE
例子还有吗？

### ISSUE THREAD

**Issue by snowflake-x** [waitingsong/node-win32-api#112]
rt，还有个问题，我想使用koffi调用一个Dll 有些函数有结构体指针参数，我该如何传递进去？

**Comment by waitingsong** [comment]
https://github.com/waitingsong/node-win32-api/blob/main/packages/win32-api/test/lib/user32/1000.RegisterClassExW.test.ts
 这个符合不？

**Comment by waitingsong** [comment]
或者这儿 https://github.com/waitingsong/node-win32-api/tree/main/packages/win32-def/test/lib/struct
