### ISSUE TITLE
Cannot find package '@waiting/shared-core'

### ISSUE THREAD

**Issue by liuhq** [waitingsong/node-win32-api#117]
like below:

![image](https://github.com/user-attachments/assets/2e16e185-8c8a-4568-9988-dfc6d1448456)

**Comment by liuhq** [comment]
I add '@waiting/shared-core' manually and resolve it. Maybe it's some dependency configuration issue?

**Comment by waitingsong** [comment]
is your project CJS ?

paste the package.json and tsconfig.json

**Comment by liuhq** [comment]
> is your project CJS ?
> 
> paste the package.json and tsconfig.json

not, it's esm (entry file `index.mjs`)

![image](https://github.com/user-attachments/assets/8e43b77d-e68b-477f-adbd-e25e01abc1ef)

![image](https://github.com/user-attachments/assets/ae24e3c5-eec2-4df8-9966-4280eeac4050)

![image](https://github.com/user-attachments/assets/52ae860f-3a12-4ec5-b186-a95db38d87f7)

then, I try to add `"type": "module"` and still throw.

I use pnpm, but I also tried it with npm. It shouldn’t be the issue with the package manager.

**Comment by waitingsong** [comment]
Fix with `v26.0.4`.
Thanks for your report :D
