### ISSUE TITLE
Having trouble with Typescript

### ISSUE THREAD

**Issue by catfo435** [waitingsong/node-win32-api#119]
I am building an application with Electron-Vite` and I encountered the following error:

```typescript
import { GetDefaultPrinter } from "win32-api/util"
console.log(await GetDefaultPrinter())
```

I get the follow typescript error:

> Cannot find module 'win32-api/util' or its corresponding type declarations.
  There are types at <path_redacted>/node_modules/win32-api/dist/index.util.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts(2307)

This is with tsconfig.node.json

```json
{
  "extends": "@electron-toolkit/tsconfig/tsconfig.node.json",
  "include": ["electron.vite.config.*", "src/main/**/*", "src/preload/**/*"],
  "compilerOptions": {
    "composite": true,
    "types": ["electron-vite/node"]
  }
}
```

If I follow the error and change the tsconfig.node.json to
```json
{
  "extends": "@electron-toolkit/tsconfig/tsconfig.node.json",
  "include": ["electron.vite.config.*", "src/main/**/*", "src/preload/**/*"],
  "compilerOptions": {
    "composite": true,
    "moduleResolution": "NodeNext",
    "target": "es2020",
    "module": "NodeNext",
    "types": ["electron-vite/node"]
  }
}
```

The error goes away in my IDE. But once I compile using `pnpm run dev` I get the following error:

>Error [ERR_REQUIRE_ESM]: require() of ES Module <path_redacted>\node_modules\.pnpm\@waiting+shared-core@23.25.5\node_modules\@waiting\shared-core\dist\index.js from <path_redacted>\node_modules\.pnpm\win32-def@26.1.0\node_modules\win32-def\dist\index.cjs not supported.
Instead change the require of index.js in<path_redacted>\node_modules\.pnpm\win32-def@26.1.0\node_modules\win32-def\dist\index.cjs to a dynamic import() which is available in all CommonJS modules.

**Comment by waitingsong** [comment]
You could provide a simple code repository.

**Comment by waitingsong** [comment]
Please try new version `26.1.1`

**Comment by catfo435** [comment]
> You could provide a simple code repository.

 I apologise I didnt see this
 
 > Please try new version 26.1.1
 
 Thank you so much. It works now! I have been trying to fix this since days. I'll close this issue now.

**Comment by waitingsong** [comment]
`win32-def` has dependencies `@waiting/shared-core` that is pure ESM.
Now i copy the code into `win32-def`
