### ISSUE TITLE
Can GetRawInputData be added ?

### ISSUE THREAD

**Issue by yadomi** [waitingsong/node-win32-api#12]
Would it be possible to add input related functions such as `GetRawInputData`, `GetRawInputDeviceList` and `GetRawInputDeviceInfo` ?

Anyhow, this is a very great package, keep up the good work !

**Comment by Njanderson** [comment]
This would require many dependencies, right?

I'm looking at GetRawInputData. It looks as if we would need to add the ability to add events (DefWindowProcA), which then would require that we define many new types, then eventually we could add GetRawInputData once we have the ability to even be notified that there is some RAWINPUT to be read in.

Does this sound correct to you?

**Comment by Njanderson** [comment]
For the latter two calls, I think that I can add these pretty easily. The author seems pretty responsive to PRs, which is nice.

**Comment by waitingsong** [comment]
The type Union is complex , i've no enough time currently.

**Comment by waitingsong** [comment]
`GetRawInputData()` added
