### ISSUE TITLE
Adding Kernel32's GetSystemTime

### ISSUE THREAD

**Issue by Njanderson** [waitingsong/node-win32-api#14]
Hey!
I am working on adding GetSystemTime, which involves my first adding to your node-win32-def project to add the FILETIME, PFILETIME, and LPFILETIME types. There are node extensions (see system-information) that use WMIC to perform tons of queries, but I would imagine we could get better performance by invoking these functions directly without having to deal with starting a console, executing WMIC, and returning. I plan to start with exposing GetSystemTime and seeing what other functions are currently exposed through executing a terminal session of WMIC.

Is this work that you would pull into your project?

Thanks,
Nick

**Comment by waitingsong** [comment]
published as win32-api@6.1.0

thanks
