### ISSUE TITLE
Could you add ChangeDisplaySettingsA ?

### ISSUE THREAD

**Issue by michael-dm** [waitingsong/node-win32-api#17]
Hello ! 

Is it possible to add ChangeDisplaySettingsA ?
If you don't have the time could you give me some insight on the steps to do it ?

Thanks !

**Comment by waitingsong** [comment]
Hi,
I have not enough time to do it this time.
If you interested in it, you should follow this:
1. add [DEVMODE Structure](http://www.jasinskionline.com/windowsapi/ref/d/devmode.html) into [win32-def](https://github.com/waitingsong/node-win32-def)
  - [data-struct](https://github.com/waitingsong/node-win32-def/blob/master/src/lib/data-struct.ts)
  - [struct.ts](https://github.com/waitingsong/node-win32-def/blob/master/src/lib/win-model/struct.ts)
2. add [function declaration](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-changedisplaysettingsa) in the file [user32](https://github.com/waitingsong/node-win32-api/blob/master/src/lib/user32/api.ts)

**Comment by waitingsong** [comment]
`ChangeDisplaySettingsExW()` added
