### ISSUE TITLE
Running tasks in vscode on Windows

### ISSUE THREAD

**Issue by Venryx** [waitingsong/node-win32-api#18]
Executing `npm run build` currently fails on Windows, since it calls `npm run clean`, which calls `rm -rf dist/*`, which fails since Windows doesn't have the `rf` command.

A simple solution is to add `shx` as a dev-dependency, then replace `rm -rf dist/*` with `shx rm -rf dist/*`.

**Comment by Venryx** [comment]
Created a pull request fixing this issue here: https://github.com/waitingsong/node-win32-api/pull/19

**Comment by waitingsong** [comment]
I run scripts `npm run clean` under `git-bash`, so `rm -rf` works.  :smile:
