### ISSUE TITLE
How to send WM_COPYDATA message with a string

### ISSUE THREAD

**Issue by TerryChan** [waitingsong/node-win32-api#25]
With node-win32-api, I tried to send a WM_COPYDATA message to another win32 application with window, but it failed, the win32 application didn't receive the messsage. But when I send WM_QUIT and WM_COMMAND mesage, it worked very well
![image](https://user-images.githubusercontent.com/5396286/78270853-f7426580-753d-11ea-8426-d23f39f2a9e2.png)

And when I used another win32 applciation to send the WM_COPYDATA message, it can received the message and the string
send WM_COPYDATA :
![image](https://user-images.githubusercontent.com/5396286/78270964-26f16d80-753e-11ea-86dc-de47f8ae9906.png)
received the message:
![image](https://user-images.githubusercontent.com/5396286/78271448-beef5700-753e-11ea-8fd8-36b83ab46e5d.png)

Do you know how to send WM_COPYDATA with a string by node-win32-api?
Or do you know is there any other method that I can send a string to another win32 application in NodeJS?
Thank you in advance.

**Comment by waitingsong** [comment]
Is it working?
```ts
rest = user32.sendMessageW(hWnd, 74, 100, Buffer.from([100]))
// or
rest = user32.sendMessageW(hWnd, 74, 100, Buffer.from(['foo\0', 'ucs2']))
```

**Comment by TerryChan** [comment]
@waitingsong No ,they doesn't work.
![image](https://user-images.githubusercontent.com/5396286/78331129-fcdc9180-75b7-11ea-9774-9af79157dfec.png)
Looks like the type of the argument is not correct

**Comment by waitingsong** [comment]
@TerryChan Would you like to provide the code.

**Comment by TerryChan** [comment]
Here is the code:
```javascript
var { Kernel32, User32 }  = require('win32-api')
// import * as ref from 'ref-napi'

const knl32 = Kernel32.load()
const user32 = User32.load()  // load all apis defined in lib/{dll}/api from user32.dll

const title = 'WindowsDesktop\0'    // null-terminated string

const lpszWindow = Buffer.from(title, 'ucs2')
const hWnd = user32.FindWindowExW(0, 0, null, lpszWindow)

if (typeof hWnd === 'number' && hWnd > 0
  || typeof hWnd === 'bigint' && hWnd > 0
  || typeof hWnd === 'string' && hWnd.length > 0
) {
  console.log('window handle: ', hWnd)

  // Send WM_QUIT message, success
  // res = user32.SendMessageW(hWnd, 2, 0, 0)

  // Send WM_COMMAND message, success
  res = user32.SendMessageW(hWnd, 273, 1000, 3)
  console.log('WM_COMMAND', res)

  // send WM_COPYDATA (74) message, fail
  res = user32.PostMessageW(hWnd, 74, 100, 100)
  // rest = user32.SendMessageW(hWnd, 74, 100, Buffer.from([100]))
  // rest = user32.SendMessageW(hWnd, 74, 100, Buffer.from(['foo\0', 'ucs2']))
  // res = user32.PostMessageW(hWnd, 74, 100, 100)

  console.log('WM_COPYDATA', res)
}
```

**Comment by waitingsong** [comment]
pls try this [demo](https://github.com/waitingsong/node-win32-api/blob/master/packages/win32-api/test/user32/60.user32.SendMessageW.test.ts#L46)  with version `^9.4.0`

**Comment by scil** [comment]
Is there any way to receive WM_COPYDATA?

```
browserWindow.hookWindowMessage(0x4A /* = WM_COPYDATA */, (wParam, lParam) => {
                console.log('wParam = ', wParam);
                console.log('lParam = ', lParam);
            });
```

only sth like
```
wParam =  <Buffer@0x0000018C305F7160 00 00 00 00 00 00 00 00>
lParam =  <Buffer@0x0000018C305F6EC0 a0 f2 cf 42 8a 00 00 00>
```

How to get the data from WM_COPYDATA?

**Comment by waitingsong** [comment]
> Is there any way to receive WM_COPYDATA?
> 
> ```
> browserWindow.hookWindowMessage(0x4A /* = WM_COPYDATA */, (wParam, lParam) => {
>                 console.log('wParam = ', wParam);
>                 console.log('lParam = ', lParam);
>             });
> ```
> 
> only sth like
> 
> ```
> wParam =  <Buffer@0x0000018C305F7160 00 00 00 00 00 00 00 00>
> lParam =  <Buffer@0x0000018C305F6EC0 a0 f2 cf 42 8a 00 00 00>
> ```
> 
> How to get the data from WM_COPYDATA?

`retrieveStructFromPtrAddress()` may help you: [demo](https://github.com/waitingsong/node-win32-api/blob/9956c55f18f89ae9d9f7d0018ef1eeb3bd89f7c9/packages/win32-api/test/70.user32.test.ts#L144)
