### ISSUE TITLE
HANDLE

### ISSUE THREAD

**Issue by TheNoim** [waitingsong/node-win32-api#3]
I try to make a simple window with this module and use the example for this. The problem is, I can't use the WNDCLASSEX Struct because of the HANDLE type. 
I only get this: 
`TypeError: could not determine a proper "type" from: "HANDLE"`

`const wClass = new Struct(DStruct.WNDCLASSEX)()`

**Comment by waitingsong** [comment]
fixed by win32-api@3.0.2
please update the version and try it again.

**Comment by TheNoim** [comment]
Fixed, Thanks.
