### ISSUE TITLE
FlashWindow & FlashWindowEx from winuser.h

### ISSUE THREAD

**Issue by ciriousjoker** [waitingsong/node-win32-api#32]
- [FlashWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-flashwindow)
- [FlashWindowEx](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-flashwindowex)

Please add support for these two

**Comment by waitingsong** [comment]
Added. 
[DEMO](https://github.com/waitingsong/node-win32-api/blob/main/packages/win32-api/test/user32/60.FlashWindowEx.test.ts)

**Comment by waitingsong** [comment]
`FlashWindows()` added.
[DEMO](https://github.com/waitingsong/node-win32-api/blob/main/packages/win32-api/test/user32/61.FlashWindow.test.ts)

**Comment by zgpio** [comment]
Please add support for [GetClassName](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getclassname)
