### ISSUE TITLE
Can you add GetCaretPos?

### ISSUE THREAD

**Issue by nnguyen01** [waitingsong/node-win32-api#33]
GetCaretPos would be super useful for a use case I'm trying to do.

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getcaretpos

Is it possible to add this?

**Comment by waitingsong** [comment]
`GetCaretPos()` added.
[DEMO](https://github.com/waitingsong/node-win32-api/blob/main/packages/win32-api/test/user32/62.GetCaretPos.test.ts)
