### ISSUE TITLE
compatible with regular JavaScript?

### ISSUE THREAD

**Issue by gittyup2018** [waitingsong/node-win32-api#38]
Is this compatible with regular or plain JavaScript? or is there a plain JavaScript version? if so can you show an example because I'm not familiar with typescript, coffeescript, all the pointless JavaScript variations, etc. and I prefer normal / regular / original JavaScript.

**Comment by waitingsong** [comment]
Yes, it supports plan js.

1. change `import` syntax to `require()`
2. remove type def

simple example
```ts
import ref from 'ref-napi'
import { DModel as M } from 'win32-api'
import { Kernel32, User32 } from 'win32-api/promise'

const knl32 = Kernel32.load()
const user32 = User32.load()

const lpszClass = Buffer.from('guard64\0', 'ucs2')
const hInstanceBuffer = ref.alloc(W.HANDLE_PVOID)
const hInstanceAddr = ref.address(hInstanceBuffer)

await knl32.GetModuleHandleExW(0, lpszClass, hInstanceAddr)

```

to

```js
const ref = require('ref-napi')
const { DModel as M } = require('win32-api')
const { Kernel32, User32  }  = require('win32-api/promise')  // <--- not sure this syntax

const knl32 = Kernel32.load()
const user32 = User32.load()

const lpszClass = Buffer.from('guard64\0', 'ucs2')
const hInstanceBuffer = ref.alloc(W.HANDLE_PVOID)
const hInstanceAddr = ref.address(hInstanceBuffer)

await knl32.GetModuleHandleExW(0, lpszClass, hInstanceAddr)

```

**Comment by waitingsong** [comment]
```js
const point = StructFactory<M.POINT>(DS.POINT)
point.x = 100
```

to

```ts
const point = StructFactory(DS.POINT)
point.x = 100
```

**Comment by gittyup2018** [comment]
Thanks for the quick reply! 

I tried your code but I get the error: 

App threw an error during load
ReferenceError: W is not defined

const hInstanceBuffer = ref.alloc(W.HANDLE_PVOID)

I don't know if makes a difference but I'm trying to use it to make an electron app,

Also I downloaded your repo (to try typescript version) and tried to run "npm run bootstrap" but it could not find lerna command.

And I'm not too familiar with Win32 API but would this module let me send text to Notepad? Can you show a SendMessage example? In regular javascript please

**Comment by waitingsong** [comment]
try :
```js
import {
  DModel as M,
  DTypes as W,
  DStruct as DS,
} from 'win32-api'
// to
const {
  DModel as M,
  DTypes as W,
  DStruct as DS,
} = require('win32-api')
```

**Comment by gittyup2018** [comment]
const {
  DModel as M,
  DTypes as W,
  DStruct as DS,
} = require('win32-api')

as syntax is not supported 

This works: 

but still same error:  W is not defined error

Notice commented out as ... line

const ref = require('ref-napi')
const { DModel,DTypes,Dstruct} = require('win32-api')
//const {DModel as M, DTypes as W,DStruct as DS} = require('win32-api')

const { Kernel32, User32  }  = require('win32-api/promise')

const knl32 = Kernel32.load()
const user32 = User32.load()

const lpszClass = Buffer.from('guard64\0', 'ucs2')
const hInstanceBuffer = ref.alloc(W.HANDLE_PVOID)
const hInstanceAddr = ref.address(hInstanceBuffer)

async function main() {
await knl32.GetModuleHandleExW(0, lpszClass, hInstanceAddr);
}

**Comment by waitingsong** [comment]
see [demo](https://github.com/waitingsong/node-win32-api/blob/main/packages/win32-api/test/user32/57.SendMessageW.GETTEXT.test.ts)
