### ISSUE TITLE
Cannot find module 'win32-def/struct.def' 

### ISSUE THREAD

**Issue by zgpio** [waitingsong/node-win32-api#40]
Change `  "types": "src/index.ts"`  to `"types": "./dist/index.d.ts"`  in `win32-api/package.json`,  the error  below disappear, but why.

```sh
$ npm run build && chcp 65001 && electron ./dist/main.js
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> electron-quick-start-typescript@1.0.0 build
> tsc

node_modules/win32-api/src/index.ts:25:26 - error TS2307: Cannot find module 'win32-def/struct.def' or its corresponding type declarations.

25 export * as DStruct from 'win32-def/struct.def'
                            ~~~~~~~~~~~~~~~~~~~~~~
node_modules/win32-api/src/index.ts:27:25 - error TS2307: Cannot find module 'win32-def/common.def' or its corresponding type declarations.
```

**Comment by waitingsong** [comment]
maybe lack of types in win32-def/packages.json.
pls try latest version v19.8.3.

**Comment by zgpio** [comment]
I tried  latest version v19.8.3，still have the same error.

**Comment by waitingsong** [comment]
Give me a sample repo to test ?

**Comment by zgpio** [comment]
Please use [hello world](https://github.com/electron/electron-quick-start-typescript),  and `yarn add win32-api` and add follow in `src/main.ts`
```
import { CS } from 'win32-api'
```
After this, execute `yarn start`, then you will find error.

**Comment by waitingsong** [comment]
![2022-08-29_151550](https://user-images.githubusercontent.com/1763067/187145046-287017d6-0eec-4cca-a8a6-393a8b6c306b.png)

It works.
Check your ts version. mine 4.7.4,  maybe something wrong with tsc v4.8.2 (I run into eslint error with other project)

**Comment by zgpio** [comment]
![image](https://user-images.githubusercontent.com/19503791/187175211-16c47405-445d-4df8-aa38-89836a739a9c.png)

Can you reproduce this problem?

**Comment by waitingsong** [comment]
Fixed it with new version and config. wait a moment.

**Comment by waitingsong** [comment]
Update:

package.json
```json
  "dependencies": {
    "win32-api": "^20.0.0",
    "ffi-napi": "^4.0.3",
    "ref-napi": "^3.0.3",
    "ref-struct-di": "^1.1.1",
    "ref-union-di": "^1.0.1"
  }

```

tsconfig.json:
```json
{
  "compilerOptions": {
   ......................
    "skipLibCheck": true
  },

}

```

**Comment by zgpio** [comment]
I have verified it, close it.
