### ISSUE TITLE
Is hMonitor supported?

### ISSUE THREAD

**Issue by rortan134** [waitingsong/node-win32-api#41]
More specifically, i'm interested in using [this](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfromwindow), is it possible?

**Comment by rortan134** [comment]
I managed to do it extending the user32 using the [ffi](https://www.npmjs.com/package/ffi-napi) for node library with this code and some structs, an implementation using this lib would be nicer though
```
const winuser32 = ffi.Library('user32.dll', {
  MonitorFromWindow: [HWND, [HANDLE, DWORD]],
  GetMonitorInfoA: ['bool', [HANDLE, ref.refType(MONITORINFO)]],
});
```

**Comment by waitingsong** [comment]
will add it later

**Comment by waitingsong** [comment]
MonitorFromWindow()  added
