### ISSUE TITLE
Unused '@ts-expect-error' directive.

### ISSUE THREAD

**Issue by zgpio** [waitingsong/node-win32-api#51]
![image](https://user-images.githubusercontent.com/19503791/218248100-942d3dbe-0a04-4006-90c3-6afe0002c7a3.png)

![image](https://user-images.githubusercontent.com/19503791/218248161-f1dacba4-ab2e-46c0-9e42-44e958029ab6.png)

**Comment by waitingsong** [comment]
try version `20.4.1`
