### ISSUE TITLE
Why is there a line length limit of 120?

### ISSUE THREAD

**Issue by dunklesToast** [waitingsong/node-win32-api#6]
Is there any reason why there is that limit with 120 Lines?

**Comment by waitingsong** [comment]
tslint.json
https://palantir.github.io/tslint/rules/max-line-length/

**Comment by dunklesToast** [comment]
Yea. I know that tslint does that. But why do we need this length? Is there any specific reason to keep it under 120?

**Comment by waitingsong** [comment]
Cause the monitor of my colleague is not bigger enough, and sometime works with laptop

**Comment by dunklesToast** [comment]
what? Why don't you scroll down?
