### ISSUE TITLE
[QUESTION] 请问有什么方式可以替换包内ref-napi和ffi-napi依赖吗

### ISSUE THREAD

**Issue by xmsz** [waitingsong/node-win32-api#63]
背景
- electron
- electron无法正常构建ffi-napi（社区共有的问题），所以用的是第三方改好的包@lwahonen/ffi-napi
- win32-api包用的是ffi-napi，所以electron项目用不了

需求
- 如何解决这个情况

我的想法
- 通过webpack那ffi-napi替换成@lwahonen/ffi-napi，我试了webpack.resolve.alias，但这个好像不能替换node_modules里
- 手动替换包内api，然后打包或者有引入，这个方法是在太麻烦了

**Comment by waitingsong** [comment]
给个最小复现仓库，我看看怎么弄比较好。

**Comment by waitingsong** [comment]
已经更换成 `koffi`  https://koffi.dev/, 支持 nodejs v18+
