### ISSUE TITLE
这个API支不支持WebView2?和SystemTrayMenu？

### ISSUE THREAD

**Issue by newghost** [waitingsong/node-win32-api#71]
可否创建一个包含WebView的Window form？
能否支持创建系统托盘图标和右键菜单？

如果能实现感觉比Electron更优秀呀

**Comment by newghost** [comment]
找到一个支持webview的库。不太清楚系统托盘图标和右键菜单能否实现？

**Comment by waitingsong** [comment]
如果是 DLL 文件，那么不用这个包你直接写 ffi 调用也行的
