### ISSUE TITLE
Debug Monitor output

### ISSUE THREAD

**Issue by genifycom** [waitingsong/node-win32-api#8]
I am looking for Kernel32 OutputDebugString. How do we extend this library to provide this very useful function?

**Comment by genifycom** [comment]
Do we add
	OutputDebugString: [W.LPTSTR],
to api.js?

**Comment by waitingsong** [comment]
You can try v3.5.1 with kernel32:OutputDebugStringW()

**Comment by githoniel** [comment]
@genifycom try `electron-rebuilder` and run 
```
cd ./node_modules/.bin && electron-rebuild --force --arch=ia32 --module-dir=../../
```
