### ISSUE TITLE
Can you add RegisterWindowMessage and BroadcastSystemMessage ?

### ISSUE THREAD

**Issue by the-Arioch** [waitingsong/node-win32-api#83]
* https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerwindowmessagew
* https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-broadcastsystemmessage

Since you already imported PostMessage and SendMessage this would be a nice addition too

**Comment by waitingsong** [comment]
added
